[package]
name = "client"
version = "0.1.0"
authors = ["devacrom"]
edition = "2018"

[lib]
name = "utils"
path = "./src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
